#!/bin/bash

echo 
echo "==========================================================="
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * *" 
echo "*                                                         *"
echo "*  Initialize submodules                                  *"
echo "*                                                         *"
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * *" 
echo 

git submodule update --init --recursive

echo 
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * *" 
echo "*                                                         *"
echo "* Install python packages                                 *"
echo "*                                                         *"
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * *" 
echo 

python -m venv .venv
source .venv/bin/activate

pip install -r requirements.txt

pip install -e ./3_jaxley

## Depending on the cuda version, install:
#pip install jax[cuda12]
#pip install jax[cuda13]

echo 
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * *" 
echo "*                                                         *"
echo "* activate environment using \`source .venv/bin/activate\`  *"
echo "*                                                         *"
echo "* GPU support by installing \`pip install jax[cuda13]\`     *"
echo "*         replace 13 by your respective cuda version!     *"
echo "*                                                         *"
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
echo "============================================================="
